
_myArray = 

	["Heli Pilot",[["SMG_03C_TR_black","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhs_weap_rsp30_green","","","",["rhs_mag_rsp30_green",1],[],""],["U_B_HeliPilotCoveralls",[["ACE_EarPlugs",2],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",5],["ACE_splint",2],["ACE_tourniquet",2],["G_Aviator",1],["50Rnd_570x28_SMG_03",1,50]]],["V_TacVest_oli",[["ACE_elasticBandage",15],["ACE_HandFlare_White",2,1],["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["SmokeShell",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["50Rnd_570x28_SMG_03",4,50]]],["OPXT_blk_117",[]],"rhsusf_hgu56p_visor_black","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_16","ItemCompass","ACE_Altimeter","NVGoggles_OPFOR"]]],
	["Heli Crew",[["SMG_03C_TR_black","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhs_weap_rsp30_green","","","",["rhs_mag_rsp30_green",1],[],""],["U_B_HeliPilotCoveralls",[["ACE_EarPlugs",2],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",5],["ACE_splint",2],["ACE_tourniquet",2],["G_Aviator",1],["50Rnd_570x28_SMG_03",1,50]]],["V_TacVest_oli",[["ACE_elasticBandage",15],["ACE_HandFlare_White",2,1],["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["SmokeShell",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["50Rnd_570x28_SMG_03",4,50]]],["B_AssaultPack_rgr",[["ACE_DefusalKit",1],["ACE_Clacker",1],["SatchelCharge_Remote_Mag",1,1]]],"rhsusf_hgu56p_visor_green","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","NVGoggles_OPFOR"]]],
	["Fixed Wing Pilot",[[],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_PilotCoveralls",[["ACE_elasticBandage",10],["ACE_EarPlugs",2],["ACE_epinephrine",2],["ACE_morphine",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",5,17]]],["V_HarnessO_gry",[["G_Aviator",1],["rhsusf_acc_omega9k",1],["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_White",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["SmokeShell",2,1],["ACE_Chemlight_UltraHiOrange",5,1],["ACE_Chemlight_HiWhite",5,1],["ACE_Chemlight_HiBlue",5,1],["ACE_Chemlight_HiGreen",5,1],[["rhs_weap_rsp30_green","","","",["rhs_mag_rsp30_green",1],[],""],1]]],["B_Parachute",[]],"H_PilotHelmetFighter_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter",""]]],
	["Arid Vehicle Commander",[["SMG_03C_TR_black","","","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",2],["ACE_CableTie",2],["ACE_tourniquet",2],["ACE_epinephrine",2],["ACE_morphine",5],["rhsusf_mag_17Rnd_9x19_FMJ",3,17]]],["rhsusf_spcs_ocp_crewman",[["ACE_elasticBandage",10],["ACE_EntrenchingTool",1],["rhsusf_acc_omega9k",1],["ACE_DefusalKit",1],["MineDetector",1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["50Rnd_570x28_SMG_03",4,50]]],["OPXT_multicam_1523",[["ToolKit",1],["SatchelCharge_Remote_Mag",1,1]]],"rhsusf_cvc_helmet","rhsusf_shemagh_gogg_tan",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","NVGoggles"]]],
	["Arid Vehicle Crew",[["SMG_03C_TR_black","","","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_mc",[["ACE_EarPlugs",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",2],["ACE_CableTie",2],["ACE_tourniquet",2],["ACE_epinephrine",2],["ACE_morphine",5],["rhsusf_mag_17Rnd_9x19_FMJ",3,17]]],["rhsusf_spcs_ocp_crewman",[["ACE_elasticBandage",10],["ACE_EntrenchingTool",1],["rhsusf_acc_omega9k",1],["ACE_DefusalKit",1],["MineDetector",1],["rhs_mag_m67",2,1],["SmokeShell",2,1],["50Rnd_570x28_SMG_03",4,50]]],["OPXT_multicam_1523",[["ToolKit",1],["SatchelCharge_Remote_Mag",1,1]]],"rhsusf_cvc_helmet","rhsusf_shemagh_gogg_tan",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","NVGoggles"]]],
	["Desert Vehicle Commander",[["rhs_weap_XM2010_d","","rhsusf_acc_anpeq16a","rhsusf_acc_premier",["rhsusf_5Rnd_300winmag_xm2010",5],[],"bipod_01_F_blk"],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_FullGhillie_ard",[["ACE_EarPlugs",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",2],["ACE_tourniquet",2],["ACE_CableTie",2],["ACE_epinephrine",2],["ACE_morphine",5],["rhsusf_mag_17Rnd_9x19_JHP",6,17]]],["V_Chestrig_rgr",[["ACE_elasticBandage",20],["rhsusf_acc_premier_anpvs27",1],["rhsusf_acc_omega9k",1],["ACE_EntrenchingTool",1],["rhsusf_acc_M2010S_d",1],["ACE_Tripod",1],["SmokeShell",2,1],["rhs_mag_m67",2,1]]],[],"rhs_booniehat2_marpatd","rhsusf_shemagh2_tan",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_12","ItemCompass","ACE_Altimeter","NVGoggles"]]],
	["Desert Vehicle Crew",[["SMG_03C_TR_black","","","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_EarPlugs",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",2],["ACE_CableTie",2],["ACE_tourniquet",2],["ACE_epinephrine",2],["ACE_morphine",5],["rhsusf_mag_17Rnd_9x19_FMJ",3,17]]],["rhsusf_spc_crewman",[["ACE_elasticBandage",10],["ACE_EntrenchingTool",1],["rhsusf_acc_omega9k",1],["ACE_DefusalKit",1],["MineDetector",1],["rhs_mag_m67",2,1],["SmokeShell",2,1]]],["B_AssaultPack_cbr",[["ToolKit",1],["50Rnd_570x28_SMG_03",4,50]]],"rhsusf_cvc_helmet","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","NVGoggles"]]],
	["Woodland Vehicle Commander",[["SMG_03C_TR_black","","","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_m81",[["ACE_EarPlugs",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",2],["ACE_CableTie",2],["ACE_tourniquet",2],["ACE_epinephrine",2],["ACE_morphine",5],["rhsusf_mag_17Rnd_9x19_FMJ",3,17]]],["rhsusf_spc_crewman",[["ACE_elasticBandage",10],["ACE_EntrenchingTool",1],["rhsusf_acc_omega9k",1],["ACE_DefusalKit",1],["MineDetector",1],["rhs_mag_m67",2,1],["SmokeShell",2,1]]],["OPXT_m81_1523",[["ToolKit",1],["SatchelCharge_Remote_Mag",1,1],["50Rnd_570x28_SMG_03",4,50]]],"rhsusf_cvc_green_helmet","rhsusf_shemagh_gogg_tan",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","NVGoggles_INDEP"]]],
	["Woodland Vehicle Crew",[["SMG_03C_TR_black","","","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_m81",[["ACE_EarPlugs",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",2],["ACE_CableTie",2],["ACE_tourniquet",2],["ACE_epinephrine",2],["ACE_morphine",5],["rhsusf_mag_17Rnd_9x19_FMJ",3,17]]],["rhsusf_spc_crewman",[["ACE_elasticBandage",10],["ACE_EntrenchingTool",1],["rhsusf_acc_omega9k",1],["ACE_DefusalKit",1],["MineDetector",1],["rhs_mag_m67",2,1],["SmokeShell",2,1]]],["B_AssaultPack_rgr",[["ToolKit",1],["50Rnd_570x28_SMG_03",4,50]]],"rhsusf_cvc_green_helmet","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","NVGoggles_INDEP"]]]

;


{
_x call ace_arsenal_fnc_addDefaultLoadout;
} forEach _myArray; 