
_myArray [
    ["JSDF Desert Squadlead",[["hlc_rifle_416D145_gl","","rhsusf_acc_anpeq15_bk","rhsusf_acc_g33_xps3",["hlc_30rnd_556x45_EPR",30],["1Rnd_HE_Grenade_shell",1],""],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Sleeve_Splinter_Desert",[["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1]]],["milgp_v_jpc_teamleader_belt_khk",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_morphine",3],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["1Rnd_Smoke_Grenade_shell",5,1],["SmokeShell",2,1],["HandGrenade",2,1],["SmokeShellBlue",2,1],["hlc_12Rnd_40SW_B_P226",1,12]]],["OPXT_oga_117",[["1Rnd_HE_Grenade_shell",20,1]]],"milgp_h_opscore_01_khk","rhs_googles_black",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["JSDF Desert AT",[["hlc_rifle_416D145","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],["launch_MRAWS_sand_F","","","",["MRAWS_HEAT_F",1],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Sleeve_Splinter_Desert",[["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1]]],["milgp_v_jpc_assaulter_belt_khk",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_morphine",3],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["HandGrenade",2,1],["SmokeShell",2,1],["hlc_12Rnd_40SW_B_P226",1,12]]],["milgp_b_patrol_01_khk",[["MRAWS_HEAT_F",2,1]]],"milgp_h_opscore_01_khk","rhs_googles_black",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["JSDF Desert Medic",[["hlc_rifle_416D145","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],[],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Sleeve_Splinter_Desert",[["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1]]],["milgp_v_jpc_medic_belt_khk",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_morphine",3],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["HandGrenade",2,1],["SmokeShell",2,1],["hlc_12Rnd_40SW_B_P226",1,12]]],["milgp_b_patrol_01_khk",[["ACE_fieldDressing",22],["ACE_epinephrine",10],["ACE_bloodIV",10],["ACE_morphine",15]]],"milgp_h_opscore_01_khk","rhs_googles_black",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["JSDF Desert NCO",[["hlc_rifle_416D145_gl","","rhsusf_acc_anpeq15_bk","rhsusf_acc_g33_xps3",["hlc_30rnd_556x45_EPR",30],["1Rnd_HE_Grenade_shell",1],""],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Sleeve_Splinter_Desert",[["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1]]],["milgp_v_jpc_teamleader_belt_khk",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_morphine",3],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["1Rnd_Smoke_Grenade_shell",5,1],["SmokeShell",2,1],["HandGrenade",2,1],["SmokeShellBlue",2,1],["hlc_12Rnd_40SW_B_P226",1,12]]],["OPXT_oga_117",[["1Rnd_HE_Grenade_shell",20,1]]],"milgp_h_opscore_01_khk","rhs_googles_black",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["JSDF Desert Support",[["hlc_rifle_416D145","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],[],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Sleeve_Splinter_Desert",[["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1]]],["milgp_v_jpc_assaulter_belt_khk",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_morphine",3],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["HandGrenade",2,1],["SmokeShell",2,1],["hlc_12Rnd_40SW_B_P226",1,12]]],["milgp_b_patrol_01_khk",[["ACE_bloodIV",3],["ACE_fieldDressing",5],["rhs_mag_100Rnd_556x45_M855A1_cmag",3,100],["rhs_mag_30Rnd_556x45_M855A1_Stanag",15,30]]],"milgp_h_opscore_01_khk","rhs_googles_black",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["JSDF Desert Autorifleman",[["hlc_rifle_M27IAR","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],[],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Sleeve_Splinter_Desert",[["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACE_Flashlight_XL50",1],["HandGrenade",2,1],["SmokeShell",1,1]]],["milgp_v_jpc_hgunner_belt_khk",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_morphine",3],["hlc_12Rnd_40SW_B_P226",1,12],["rhs_mag_100Rnd_556x45_M855A1_cmag",5,100]]],[],"milgp_h_opscore_01_khk","rhs_googles_black",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]]
];


{
_x call ace_arsenal_fnc_addDefaultLoadout;
} forEach _myArray; 