 
_myArray = [
	["Helicopter Pilot",[["SMG_03C_TR_black","","","SMA_MICRO_T2",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_HeliPilotCoveralls",[["ACE_EarPlugs",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",1],["ACE_Flashlight_XL50",1],["ACE_fieldDressing",6],["ACE_IR_Strobe_Item",1]]],["USP_VEST_STRANDHOGG_RGR",[["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_White",1,1],["HandGrenade",1,1],["SmokeShell",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["50Rnd_570x28_SMG_03",5,50],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["OPXT_ogao_117",[["ToolKit",1]]],"rhsusf_hgu56p_visor_black","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]],
	["Woodland Tank Commander",[["SMG_03C_TR_black","","SMA_SFFL_BLK","SMA_MICRO_T2",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_m81",[["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",1],["ACE_fieldDressing",6],["ACE_IR_Strobe_Item",1],["ACE_morphine",3],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["USP_VEST_STRANDHOGG_RGR",[["ACE_EntrenchingTool",1],["ACE_tourniquet",5],["rhsusf_acc_omega9k",1],["rhs_mag_m67",1,1],["SmokeShellBlue",1,1],["SmokeShell",1,1],["50Rnd_570x28_SMG_03",4,50]]],["OPXT_m81_117",[["ToolKit",1],["ACE_DefusalKit",1],["MineDetector",1]]],"rhsusf_cvc_green_helmet","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]],
	["Woodland Tank Gunner/Driver",[["SMG_03C_TR_black","","SMA_SFFL_BLK","SMA_MICRO_T2",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_m81",[["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",1],["ACE_fieldDressing",6],["ACE_IR_Strobe_Item",1],["ACE_morphine",3],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["USP_VEST_STRANDHOGG_RGR",[["ACE_EntrenchingTool",1],["ACE_tourniquet",5],["rhsusf_acc_omega9k",1],["rhs_mag_m67",1,1],["SmokeShellBlue",1,1],["SmokeShell",1,1],["50Rnd_570x28_SMG_03",4,50]]],["B_AssaultPack_rgr",[["ToolKit",1],["ACE_DefusalKit",1],["MineDetector",1]]],"rhsusf_cvc_green_helmet","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]],
	["Desert Tank Commander",[["SMG_03C_TR_black","","SMA_SFFL_BLK","SMA_MICRO_T2",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_tan",[["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",1],["ACE_fieldDressing",6],["ACE_IR_Strobe_Item",1],["ACE_morphine",3],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["USP_VEST_STRANDHOGG_ATXAU",[["ACE_EntrenchingTool",1],["ACE_tourniquet",5],["rhsusf_acc_omega9k",1],["rhs_mag_m67",1,1],["SmokeShellBlue",1,1],["SmokeShell",1,1],["50Rnd_570x28_SMG_03",4,50]]],["OPXT_oga_117",[["ToolKit",1],["ACE_DefusalKit",1],["MineDetector",1]]],"rhsusf_cvc_helmet","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]],
	["Desert Tank Gunner/Driver",[["SMG_03C_TR_black","","SMA_SFFL_BLK","SMA_MICRO_T2",["50Rnd_570x28_SMG_03",50],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_g3_tan",[["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_splint",1],["ACE_tourniquet",1],["ACE_fieldDressing",6],["ACE_IR_Strobe_Item",1],["ACE_morphine",3],["rhsusf_mag_17Rnd_9x19_JHP",2,17]]],["USP_VEST_STRANDHOGG_ATXAU",[["ACE_EntrenchingTool",1],["ACE_tourniquet",5],["rhsusf_acc_omega9k",1],["rhs_mag_m67",1,1],["SmokeShellBlue",1,1],["SmokeShell",1,1],["50Rnd_570x28_SMG_03",4,50]]],["B_AssaultPack_cbr",[["ToolKit",1],["ACE_DefusalKit",1],["MineDetector",1]]],"rhsusf_cvc_helmet","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]],
	["Fixed Wing Pilot",[[],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_PilotCoveralls",[["ACE_fieldDressing",6],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1],["rhsusf_mag_17Rnd_9x19_FMJ",2,17]]],["V_Pocketed_black_F",[["rhsusf_acc_omega9k",1],["SmokeShellBlue",2,1],["Chemlight_blue",1,1],["SmokeShell",1,1]]],["B_Parachute",[]],"H_PilotHelmetFighter_B","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter",""]]]

];


{
_x call ace_arsenal_fnc_addDefaultLoadout;
} forEach _myArray; 