 
_myArray = [
    ["Woodland Squadleader",[["hlc_rifle_416D145_gl","","rhsusf_acc_anpeq15_bk","rhsusf_acc_g33_xps3",["hlc_30rnd_556x45_EPR",30],["1Rnd_HE_Grenade_shell",1],""],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Splinter",[["1Rnd_HE_Grenade_shell",8,1]]],["milgp_v_marciras_teamleader_belt_rgr",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",4],["ACE_morphine",3],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["hlc_12Rnd_40SW_B_P226",2,12],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["SmokeShellBlue",2,1],["rhs_mag_m67",2,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_HE_Grenade_shell",10,1]]],["OPXT_ogao_1523",[["1Rnd_HE_Grenade_shell",2,1]]],"milgp_h_opscore_01_RGR_hexagon","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Woodland Medic",[["hlc_rifle_416D145","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Splinter",[]],["milgp_v_marciras_medic_belt_rgr",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_morphine",3],["rhs_mag_m67",2,1],["SmokeShell",1,1],["hlc_12Rnd_40SW_B_P226",2,12],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30]]],["Rainman_Kitbag_Splinter",[["ACE_fieldDressing",30],["ACE_morphine",15],["ACE_epinephrine",10],["ACE_bloodIV",10]]],"milgp_h_opscore_01_RGR_hexagon","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Woodland Autorifleman",[["hlc_rifle_M27IAR","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["rhs_mag_100Rnd_556x45_M855_cmag",100],[],"HLC_bipod_UTGShooters"],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Splinter",[]],["milgp_v_marciras_hgunner_belt_rgr",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_morphine",3],["hlc_12Rnd_40SW_B_P226",2,12],["rhs_mag_100Rnd_556x45_M855_cmag",6,100],["rhs_mag_m67",2,1],["SmokeShell",1,1]]],[],"milgp_h_opscore_01_RGR_hexagon","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Woodland Support",[["hlc_rifle_416D145","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Splinter",[]],["milgp_v_mmac_hgunner_belt_rgr",[["ACE_fieldDressing",8],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_morphine",3],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Clacker",1],["ACE_Flashlight_XL50",1],["MineDetector",1],["rhs_mag_m67",2,1],["SmokeShell",1,1],["hlc_12Rnd_40SW_B_P226",2,12],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30]]],["milgp_b_patrol_01_rgr",[["ACE_fieldDressing",10],["ACE_bloodIV",4],["ACE_epinephrine",5],["ACE_morphine",5],["MRAWS_HEAT_F",1,1],["rhsusf_m112_mag",4,1],["rhs_mag_30Rnd_556x45_M855_Stanag",20,30]]],"milgp_h_opscore_01_RGR_hexagon","rhs_ess_black",[],["ItemMap","","","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Woodland Rocket Specialist",[["hlc_rifle_416D145","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],["launch_MRAWS_green_F","","","",["MRAWS_HEAT_F",1],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Splinter",[]],["milgp_v_mmac_hgunner_belt_rgr",[["ACE_fieldDressing",8],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_morphine",3],["rhs_mag_m67",2,1],["SmokeShell",1,1],["hlc_12Rnd_40SW_B_P226",2,12],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30]]],["rhsusf_falconii",[["MRAWS_HEAT_F",2,1]]],"milgp_h_opscore_01_RGR_hexagon","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Woodland NCO ",[["hlc_rifle_416D145_gl","","rhsusf_acc_anpeq15_bk","rhsusf_acc_g33_xps3",["hlc_30rnd_556x45_EPR",30],["1Rnd_HE_Grenade_shell",1],""],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Splinter",[["1Rnd_HE_Grenade_shell",8,1]]],["milgp_v_marciras_teamleader_belt_rgr",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",4],["ACE_morphine",3],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["hlc_12Rnd_40SW_B_P226",2,12],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["SmokeShellBlue",2,1],["rhs_mag_m67",2,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_HE_Grenade_shell",10,1]]],["OPXT_ogao_1523",[["1Rnd_HE_Grenade_shell",2,1]]],"milgp_h_opscore_01_RGR_hexagon","rhs_ess_black",["Laserdesignator_01_khk_F","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Woodland Weapon Squad ",[["hlc_rifle_416D10C","","rhsusf_acc_anpeq15_bk","rhsusf_acc_T1_high",["hlc_30rnd_556x45_EPR",30],[],""],["UK3CB_BAF_Javelin_Slung_Tube","","","",[],[],""],["hlc_pistol_P226R_40Combat","","acc_flashlight_pistol","HLC_Optic_Romeo1_RX",["hlc_12Rnd_40SW_B_P226",12],[],""],["Rainman_Combat_Fatigues_Splinter",[]],["milgp_v_jpc_assaulter_belt_rgr",[["ACE_fieldDressing",8],["ACE_EarPlugs",1],["ACE_CableTie",2],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_morphine",3],["SmokeShell",1,1],["rhs_mag_m67",2,1],["hlc_12Rnd_40SW_B_P226",2,12],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30]]],[],"milgp_h_opscore_01_RGR_hexagon","rhs_ess_black",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]]
];


{
_x call ace_arsenal_fnc_addDefaultLoadout;
} forEach _myArray; 