
_myArray = [
    ["Desert Squadleader",[["SMA_M4_GL","","SMA_SFFL_BLK","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1],["ACE_EntrenchingTool",1]]],["rhsusf_spc_patchless_radio",[["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["rhs_mag_m67",2,1],["SmokeShell",2,1],["SmokeShellBlue",2,1],["ACE_HandFlare_White",1,1]]],["OPXT_oga_117",[["1Rnd_HE_Grenade_shell",10,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_SmokeBlue_Grenade_shell",2,1],["ACE_40mm_Flare_white",2,1]]],"rhsusf_lwh_helmet_marpatd","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_20","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Desert Medic",[["SMA_M4MOE","","SMA_SFFL_BLK","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1],["ACE_EntrenchingTool",1]]],["rhsusf_spc_patchless",[["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["SmokeShell",2,1],["rhs_mag_m67",1,1],["ACE_HandFlare_White",1,1]]],["B_Kitbag_cbr",[["ACE_fieldDressing",30],["ACE_bloodIV",10],["ACE_epinephrine",15],["ACE_morphine",20],["ACE_splint",10],["ACE_tourniquet",10]]],"rhsusf_lwh_helmet_marpatd","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Desert Autorifleman",[["rhs_weap_m249_pip","","","SMA_BARSKA",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_saw_bipod"],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1],["ACE_EntrenchingTool",1]]],["rhsusf_spc_mg",[["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhsusf_200Rnd_556x45_box",1,200],["SmokeShell",1,1],["rhs_mag_m67",2,1],["ACE_HandFlare_White",1,1]]],["B_AssaultPack_cbr",[["rhsusf_200Rnd_556x45_box",3,200]]],"rhsusf_lwh_helmet_marpatd","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_23","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Desert Support(Default)",[["SMA_M4MOE","","SMA_SFFL_BLK","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1]]],["rhsusf_spc_rifleman",[["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["SmokeShell",2,1],["rhs_mag_m67",1,1],["ACE_HandFlare_White",1,1]]],["B_Kitbag_cbr",[["ACE_fieldDressing",15],["ACE_bloodIV",5],["ACE_epinephrine",5],["ACE_morphine",10],["ACE_splint",5],["ACE_tourniquet",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["rhsusf_200Rnd_556x45_box",1,200]]],"rhsusf_lwh_helmet_marpatd","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_24","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Desert Anti-Tank",[["SMA_M4MOE","","SMA_SFFL_BLK","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],["launch_MRAWS_sand_F","","","",["MRAWS_HEAT_F",1],[],""],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1]]],["rhsusf_spc_patchless",[["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_m67",2,1],["SmokeShell",1,1],["ACE_HandFlare_White",1,1]]],["B_Kitbag_cbr",[["MRAWS_HEAT_F",2,1],["MRAWS_HEAT55_F",1,1]]],"rhsusf_lwh_helmet_marpatd","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_25","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Desert NCO",[["SMA_M4_GL","","SMA_SFFL_BLK","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1],["Laserbatteries",1,1]]],["rhsusf_spc_teamleader",[["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["SmokeShellBlue",2,1],["rhs_mag_m67",1,1],["SmokeShell",2,1],["ACE_HandFlare_White",1,1],["Laserbatteries",4,1]]],["OPXT_oga_117",[["1Rnd_HE_Grenade_shell",10,1],["1Rnd_Smoke_Grenade_shell",5,1],["1Rnd_SmokeBlue_Grenade_shell",2,1],["ACE_40mm_Flare_white",2,1]]],"rhsusf_lwh_helmet_marpatd","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","tf_anprc152_28","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Desert Support(Marksmen)",[["rhs_weap_m14ebrri","","SMA_SFFL_BLK","ACE_optic_LRPS_PIP",["rhsusf_20Rnd_762x51_m993_Mag",20],[],"rhsusf_acc_harris_bipod"],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1]]],["rhsusf_spc_rifleman",[["rhsusf_mag_17Rnd_9x19_JHP",2,17],["SmokeShell",2,1],["rhs_mag_m67",1,1],["ACE_HandFlare_White",1,1],["rhsusf_20Rnd_762x51_m993_Mag",6,20]]],["B_Kitbag_cbr",[["ACE_fieldDressing",15],["ACE_bloodIV",5],["ACE_epinephrine",5],["ACE_morphine",10],["ACE_splint",5],["ACE_tourniquet",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["rhsusf_200Rnd_556x45_box",1,200]]],"rhsusf_lwh_helmet_marpatd","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_30","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
    ["Desert Support(Demolition)",[["SMA_M4MOE","","SMA_SFFL_BLK","SMA_BARSKA",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["rhs_uniform_FROG01_d",[["ACE_fieldDressing",6],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_EntrenchingTool",1],["ACE_IR_Strobe_Item",1],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",3],["ACE_splint",1],["ACE_tourniquet",1]]],["rhsusf_spc_rifleman",[["ACE_DefusalKit",1],["ACE_Clacker",1],["MineDetector",1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30],["SmokeShell",2,1],["rhs_mag_m67",1,1],["ACE_HandFlare_White",1,1]]],["B_Kitbag_cbr",[["ACE_fieldDressing",10],["ACE_bloodIV",5],["ACE_epinephrine",5],["ACE_morphine",4],["ACE_splint",4],["ACE_tourniquet",4],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["rhsusf_m112x4_mag",2,1]]],"rhsusf_lwh_helmet_marpatd","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_32","ItemCompass","ItemWatch","rhsusf_ANPVS_15"]]],
];


{
_x call ace_arsenal_fnc_addDefaultLoadout;
} forEach _myArray; 