 
_myArray = [
	["Heli Pilot",[["SMG_03C_TR_black","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhs_weap_rsp30_green","","","",["rhs_mag_rsp30_green",1],[],""],["U_B_HeliPilotCoveralls",[["ACE_EarPlugs",2],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",5],["ACE_splint",2],["ACE_tourniquet",2],["G_Aviator",1],["50Rnd_570x28_SMG_03",1,50]]],["V_TacVest_oli",[["ACE_elasticBandage",15],["ACE_HandFlare_White",2,1],["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["SmokeShell",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["50Rnd_570x28_SMG_03",4,50]]],["OPXT_blk_117",[["ToolKit",1]]],"rhsusf_hgu56p_visor_black","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]],
	["Heli Crew",[["SMG_03C_TR_black","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_mrds",["50Rnd_570x28_SMG_03",50],[],""],[],["rhs_weap_rsp30_green","","","",["rhs_mag_rsp30_green",1],[],""],["U_B_HeliPilotCoveralls",[["ACE_EarPlugs",2],["ACE_epinephrine",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["ACE_morphine",5],["ACE_splint",2],["ACE_tourniquet",2],["G_Aviator",1],["50Rnd_570x28_SMG_03",1,50]]],["V_TacVest_oli",[["ACE_elasticBandage",15],["ACE_HandFlare_White",2,1],["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["SmokeShell",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["50Rnd_570x28_SMG_03",4,50]]],["B_AssaultPack_rgr",[["ToolKit",1]]],"rhsusf_hgu56p_visor_green","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]],
	["Fixed Wing Pilot",[[],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["U_B_PilotCoveralls",[["ACE_elasticBandage",10],["ACE_EarPlugs",2],["ACE_epinephrine",2],["ACE_morphine",5],["ACE_tourniquet",2],["ACE_splint",2],["ACE_Flashlight_XL50",1],["ACE_MapTools",1],["rhsusf_mag_17Rnd_9x19_FMJ",5,17]]],["V_HarnessO_gry",[["G_Aviator",1],["rhsusf_acc_omega9k",1],["ACE_HandFlare_Green",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_White",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["SmokeShell",2,1],["ACE_Chemlight_UltraHiOrange",5,1],["ACE_Chemlight_HiWhite",5,1],["ACE_Chemlight_HiBlue",5,1],["ACE_Chemlight_HiGreen",5,1],[["rhs_weap_rsp30_green","","","",["rhs_mag_rsp30_green",1],[],""],1]]],["B_Parachute",[]],"H_PilotHelmetFighter_B","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152_28","ItemCompass","ACE_Altimeter",""]]]
	
];


{
_x call ace_arsenal_fnc_addDefaultLoadout;
} forEach _myArray; 